- hosts: localhost
  tasks:
    - name: Установить Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Запустить контейнер с приложением
      docker_container:
        name: js_app
        image: "node:14"  # Используем корректный образ Node.js
        state: started
        ports:
          - "3000:3000"
        volumes:
          - "./simple-js-project:/app"  # Монтируем папку с кодом в контейнер
        working_dir: /app  # Устанавливаем рабочую директорию
        entrypoint: "/bin/bash -c 'npm install && node server.js'"
